# docker-compose.opensearch.yml
services:
  opensearch:
    image: opensearchproject/opensearch:2
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports: ["9200:9200"]
  dashboards:
    image: opensearchproject/opensearch-dashboards:2
    ports: ["5601:5601"]
